Repository rstudio/leaflet, pull requests merged in 2018-11, with the labels that each got.

#575 update st to fix known vulnerability
  docs/libs/leaflet-omnivore/package.json
  inst/htmlwidgets/lib/leaflet-omnivore/package.json
Labels: difficulty: novice, effort: low, priority: high

#587 Upgrade leaflet-providers to 1.4.0
  NEWS
  data/providers.details.rda
  data/providers.rda
  inst/htmlwidgets/lib/leaflet-providers/leaflet-providers.js
  inst/htmlwidgets/lib/leaflet-providers/package.json
  inst/htmlwidgets/lib/leaflet-providers/providers.json
Labels: QA, priority: high

#568 to make addMiniMap accessible within other packages
  NEWS
  R/plugin-minimap.R
Labels: QA, difficulty: advanced, effort: low
